databases:
  - name: energy-db
    plan: free
    databaseName: energy_db
    user: energy_user

services:
  - type: web
    name: energy-api
    plan: free
    runtime: docker
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: energy-db
          property: connectionString
